# Generated by Django 4.2.30 on 2026-06-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название активности')),
                ('category', models.CharField(choices=[('transport', 'Транспорт'), ('energy', 'Энергия'), ('food', 'Питание'), ('shopping', 'Покупки')], max_length=20, verbose_name='Категория')),
                ('co2_factor', models.FloatField(verbose_name='Коэффициент выбросов (кг CO₂ на ед.)')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения (км, кВт·ч, кг)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип активности',
                'verbose_name_plural': 'Типы активностей',
            },
        ),
        migrations.CreateModel(
            name='EcoGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.FloatField(verbose_name='Лимит кг CO₂ в месяц')),
                ('start_date', models.DateField(verbose_name='Дата начала отслеживания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_goal', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эко-цель',
                'verbose_name_plural': 'Эко-цели',
            },
        ),
        migrations.CreateModel(
            name='CarbonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата активности')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.activitytype', verbose_name='Тип активности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись об активности',
                'verbose_name_plural': 'Записи об активностях',
                'ordering': ['-date'],
            },
        ),
    ]
